name: "Data Dictionary"
description: "Generate and check freshness of data dictionaries"

inputs:
  store-name:
    description: "Name of the data store."
    required: true
  store-type:
    description: "Type of the data store."
    required: true
  tool-type:
    description: "Type of the data tool (e.g. migration)."
    required: true
  tool-path:
    description: "Path to the data tool files (e.g. migration)."
    required: true
  repo-token:
    description: "GitHub auth token for pull request comments (NOT for commits)."
    required: false
    default: ${{ github.token }}
  required-roles:
    description: "Any user roles which the application expects to exist before migrating. Separate with whitespace if multiple are required, e.g. `admin develop`."
    required: false

runs:
  using: "composite"
  steps:
    - run: pip3 install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - run: ${{ github.action_path }}/action.sh
      shell: bash
      env:
        STORE_NAME: ${{ inputs.store-name }}
        STORE_TYPE: ${{ inputs.store-type }}
        EXCLUDE_TABLES: ${{ inputs.exclude-tables }}
        TOOL_TYPE: ${{ inputs.tool-type }}
        TOOL_PATH: ${{ inputs.tool-path }}
        REQUIRED_ROLES: ${{ inputs.required-roles }}
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        GITHUB_PULL: ${{ github.event.pull_request.number }}
