name: "Data Dictionary"
description: "Generate and check freshness of data dictionaries"

inputs:
  store-name:
    description: "Name of the data store."
    required: true
  store-type:
    description: "Type of the data store."
    required: true
  tool-type:
    description: "Type of the data tool (e.g. migration)."
    required: true
  tool-path:
    description: "Path to the data tool files (e.g. migration)."
    required: true
  repo-token:
    description: "GitHub auth token for pull request comments (NOT for commits)."
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - run: pip3 install -r ./requirements.txt
      shell: bash

    - run: ${{ github.action_path }}/scripts/generate.sh
      shell: bash
      env:
        STORE_NAME: ${{ inputs.store-name }}
        STORE_TYPE: ${{ inputs.store-type }}
        TOOL_TYPE: ${{ inputs.tool-type }}
        TOOL_PATH: ${{ inputs.tool-path }}

    - run: ${{ github.action_path }}/scripts/post.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        GITHUB_PULL: ${{ github.event.pull_request.number }}
