[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true

[tool.pylint.master]
disable = ["R", "C"]
