[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true

[tool.pylint.master]
disable = ["R", "C"]

[tool.isort]
profile = "black"
src_paths = ["action"]
skip_gitignore = true
