name: validate

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        if: github.event_name == 'pull_request'
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Requirements
        run: make requirements

      - name: Formatting check (black)
        run: make check-fmt

      - name: Imports sorting check (isort)
        run: make check-imports

      - name: Lint check (pylint)
        run: make check-lint

      - name: Type check (mypy)
        run: make check-type
